"""
분석 결과를 _research/ 폴더에 마크다운 + JSON으로 저장
HTML 보고서 저장은 html_reporter.py 참고
"""

from __future__ import annotations

import json
from pathlib import Path

from .models import FullCrawlAnalysis

SEVERITY_EMOJI = {"high": "🔴", "medium": "🟡", "low": "🟢"}


def _bar(ratio: float, width: int = 20) -> str:
    filled = round(ratio * width)
    return "█" * filled + "░" * (width - filled)


def render_markdown(analysis: FullCrawlAnalysis) -> str:
    p = analysis.product_info
    s = analysis.sentiment
    u = analysis.usage_context
    v = analysis.voc
    m = analysis.marketing_insight

    lines: list[str] = []

    # 헤더
    lines += [
        f"# {p.product_name or '제품'} 리뷰 분석 보고서",
        f"> 플랫폼: {p.platform}  |  분석일: {analysis.analyzed_at}  |  분석 리뷰: {p.crawled_reviews}개",
        f"> URL: {p.url}",
        "",
        "---",
        "",
    ]

    # 1. 제품 기본 정보
    lines += [
        "## 1. 제품 기본 정보",
        "",
        f"| 항목 | 내용 |",
        f"|------|------|",
        f"| 브랜드 | {p.brand or '-'} |",
        f"| 카테고리 | {p.category or '-'} |",
        f"| 가격 | {p.price_display or '-'} |",
        f"| 평균 별점 | {f'{p.rating:.1f}점' if p.rating else '-'} |",
        f"| 전체 리뷰 수 | {p.total_reviews:,}개 |",
        f"| 분석 리뷰 수 | {p.crawled_reviews}개 |",
        "",
        "---",
        "",
    ]

    # 2. 감성 분석
    lines += [
        "## 2. 감성 분석",
        "",
        f"| 감성 | 비율 | 시각화 |",
        f"|------|------|--------|",
        f"| 긍정 | {s.positive_ratio:.0%} | {_bar(s.positive_ratio)} |",
        f"| 부정 | {s.negative_ratio:.0%} | {_bar(s.negative_ratio)} |",
        f"| 중립 | {s.neutral_ratio:.0%} | {_bar(s.neutral_ratio)} |",
        "",
        f"**종합 감성**: {s.overall_sentiment}",
        f"**한 줄 요약**: {s.sentiment_summary}",
        "",
        f"**긍정 키워드**: {', '.join(s.positive)}",
        f"**부정 키워드**: {', '.join(s.negative)}",
        f"**중립 키워드**: {', '.join(s.neutral)}",
        "",
        "---",
        "",
    ]

    # 3. 사용 맥락 분석
    lines += [
        "## 3. 사용 맥락 분석",
        "",
        f"**주 사용자 유형**: {u.primary_user_type}",
        f"**타겟 마케팅 방향**: {u.target_marketing_direction}",
        f"**최적 광고 타이밍**: {u.best_timing}",
        "",
    ]
    for section_name, patterns in [
        ("사용 시간대/계절", u.time_patterns),
        ("사용 장소/환경", u.place_patterns),
        ("구매 계기/상황", u.trigger_patterns),
    ]:
        if patterns:
            lines.append(f"### {section_name}")
            for p_item in patterns:
                lines += [
                    f"- **{p_item.pattern}** ({p_item.frequency})",
                    f'  > "{p_item.representative_quote}"' if p_item.representative_quote else "",
                ]
            lines.append("")

    lines += ["---", ""]

    # 4. VOC
    lines += [
        "## 4. 불만 포인트 VOC",
        "",
        f"**핵심 불만**: {v.recurring_complaint}",
    ]
    if v.critical_dealbreaker:
        lines.append(f"**치명적 약점**: {v.critical_dealbreaker}")
    lines.append("")

    for i, issue in enumerate(v.top_issues, 1):
        icon = SEVERITY_EMOJI.get(issue.severity, "⚪")
        lines += [
            f"### {i}. {issue.keyword} {icon}",
            f"- **카테고리**: {issue.category}",
            f"- **설명**: {issue.description}",
            f"- **빈도**: {issue.frequency}건  |  **심각도**: {issue.severity}",
        ]
        for q in issue.quotes:
            lines.append(f'  > "{q}"')
        if issue.improvement_suggestion:
            lines.append(f"- **개선 제안**: {issue.improvement_suggestion}")
        lines.append("")

    lines += ["---", ""]

    # 5. 마케팅 인사이트
    lines += [
        "## 5. 마케팅 인사이트 & 광고 카피",
        "",
        "### 긍정 기반 메인 후킹 카피",
        "",
    ]
    for i, copy in enumerate(m.hook_copy_from_positive, 1):
        lines += [
            f"**카피 #{i}** [{copy.copy_type}] → {copy.channel}",
            f"| 헤드라인 | **{copy.headline}** |",
            f"|----------|------|",
            f"| 서브카피 | {copy.sub_copy} |",
            f"| 근거 | {copy.rationale} |",
            "",
        ]

    lines += ["### 부정 반전 신뢰 보완 카피", ""]
    for i, copy in enumerate(m.trust_copy_from_negative, 1):
        lines += [
            f"**카피 #{i}** [{copy.copy_type}] → {copy.channel}",
            f"| 헤드라인 | **{copy.headline}** |",
            f"|----------|------|",
            f"| 서브카피 | {copy.sub_copy} |",
            f"| 근거 | {copy.rationale} |",
            "",
        ]

    lines += [
        "### 기회 분석",
        "",
        f"**미충족 니즈**: {m.opportunity_gap}",
        f"**추천 콘텐츠 주제**: {m.recommended_content_theme}",
        f"**대성쎌틱 어필 포인트**: {m.competitive_advantage_hint}",
        "",
        "---",
        "",
        f"*Generated by 대성쎌틱에너시스 리뷰 크롤러 | {analysis.analyzed_at}*",
    ]

    return "\n".join(lines)


def save_markdown(analysis: FullCrawlAnalysis, output_dir: str | Path) -> Path:
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    safe_name = (
        (analysis.product_info.product_name or "report")
        .replace("/", "_").replace(" ", "_")[:40]
    )
    filename = f"{analysis.analyzed_at}_{safe_name}_리뷰분석.md"
    filepath = output_dir / filename
    filepath.write_text(render_markdown(analysis), encoding="utf-8")
    print(f"[reporter] 마크다운 저장: {filepath}")
    return filepath


def save_json(analysis: FullCrawlAnalysis, output_dir: str | Path) -> Path:
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    safe_name = (
        (analysis.product_info.product_name or "report")
        .replace("/", "_").replace(" ", "_")[:40]
    )
    filename = f"{analysis.analyzed_at}_{safe_name}_분석데이터.json"
    filepath = output_dir / filename
    filepath.write_text(
        analysis.model_dump_json(indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    print(f"[reporter] JSON 저장: {filepath}")
    return filepath
